Adjust FEMUG-PE informations
braziljs/femug pull request #112
Opened 2019-07-01 12:36 UTC by clovisdasilvaneto

Actually, there's a long time that this information should be fixed but we forgot to fix it (it's arraound 3 years that is outdated).

2019-07-01 20:46 UTC, danielfilho approved these changes

2019-07-01 20:47 UTC, danielfilho commented
Can you also update `Lista.md`?

2019-07-01 20:47 UTC, danielfilho requested changes
can you update `Lista.md` also?

2019-07-02 08:43 UTC, clovisdasilvaneto commented
For sure @danielfilho

2019-07-03 11:51 UTC, danielfilho approved these changes

2019-07-31 14:33 UTC, merged